/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ModelsModelVersioning {
    'commitHash'?: string;
    'commitMessage'?: string;
    'createdAt'?: string;
    'dependency'?: { [key: string]: any; };
    'id'?: string;
    'inputFormat'?: { [key: string]: any; };
    'modelId'?: string;
    'nodeReward'?: number;
    'outputFormat'?: { [key: string]: any; };
    'platform'?: string;
    'sysRequire'?: { [key: string]: any; };
    'testResult'?: { [key: string]: any; };
    'updatedAt'?: string;
    'verifyStatus'?: string;
    'verifyTaskId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commitHash",
            "baseName": "commit_hash",
            "type": "string"
        },
        {
            "name": "commitMessage",
            "baseName": "commit_message",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "dependency",
            "baseName": "dependency",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "inputFormat",
            "baseName": "input_format",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "string"
        },
        {
            "name": "nodeReward",
            "baseName": "node_reward",
            "type": "number"
        },
        {
            "name": "outputFormat",
            "baseName": "output_format",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string"
        },
        {
            "name": "sysRequire",
            "baseName": "sys_require",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "testResult",
            "baseName": "test_result",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "verifyStatus",
            "baseName": "verify_status",
            "type": "string"
        },
        {
            "name": "verifyTaskId",
            "baseName": "verify_task_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ModelsModelVersioning.attributeTypeMap;
    }
}

