/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelsPlatformTask } from './modelsPlatformTask';

export class ModelsModelVersioningGroupLite {
    /**
    * Dependency        map[string]interface{} `json:\"dependency\"`
    */
    'commitHash'?: string;
    /**
    * TestResult        map[string]interface{} `json:\"test_result\"` InputFormat       map[string]interface{} `json:\"input_format\"` OutputFormat      map[string]interface{} `json:\"output_format\"` SysRequired       map[string]interface{} `json:\"sys_require\"`
    */
    'commitMessage'?: string;
    'isActive'?: boolean;
    'lastCheckedAt'?: string;
    'modelId'?: string;
    'pendingPlatforms'?: Array<ModelsPlatformTask>;
    'rejectedPlatforms'?: Array<ModelsPlatformTask>;
    'verifiedPlatforms'?: Array<ModelsPlatformTask>;
    'verifyStatus'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commitHash",
            "baseName": "commit_hash",
            "type": "string"
        },
        {
            "name": "commitMessage",
            "baseName": "commit_message",
            "type": "string"
        },
        {
            "name": "isActive",
            "baseName": "is_active",
            "type": "boolean"
        },
        {
            "name": "lastCheckedAt",
            "baseName": "last_checked_at",
            "type": "string"
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "string"
        },
        {
            "name": "pendingPlatforms",
            "baseName": "pending_platforms",
            "type": "Array<ModelsPlatformTask>"
        },
        {
            "name": "rejectedPlatforms",
            "baseName": "rejected_platforms",
            "type": "Array<ModelsPlatformTask>"
        },
        {
            "name": "verifiedPlatforms",
            "baseName": "verified_platforms",
            "type": "Array<ModelsPlatformTask>"
        },
        {
            "name": "verifyStatus",
            "baseName": "verify_status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ModelsModelVersioningGroupLite.attributeTypeMap;
    }
}

