/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ModelsApiKeyInfo {
    'apiPrice'?: number;
    'commitHash'?: string;
    'inputFormat'?: { [key: string]: any; };
    'modelDescription'?: string;
    'modelId'?: string;
    'outputFormat'?: { [key: string]: any; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiPrice",
            "baseName": "api_price",
            "type": "number"
        },
        {
            "name": "commitHash",
            "baseName": "commit_hash",
            "type": "string"
        },
        {
            "name": "inputFormat",
            "baseName": "input_format",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "modelDescription",
            "baseName": "model_description",
            "type": "string"
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "string"
        },
        {
            "name": "outputFormat",
            "baseName": "output_format",
            "type": "{ [key: string]: any; }"
        }    ];

    static getAttributeTypeMap() {
        return ModelsApiKeyInfo.attributeTypeMap;
    }
}

