/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelsCommitMeta } from './modelsCommitMeta';
import { ModelsCommitStats } from './modelsCommitStats';
import { ModelsRepoCommit } from './modelsRepoCommit';
import { ModelsUser } from './modelsUser';

export class ModelsCommit {
    'author'?: ModelsUser;
    'commitAffectedFiles'?: Array<string>;
    'commitData'?: ModelsUser;
    'commitMeta'?: ModelsCommitMeta;
    'parents'?: Array<ModelsCommitMeta>;
    'repoCommit'?: ModelsRepoCommit;
    'stats'?: ModelsCommitStats;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "author",
            "baseName": "author",
            "type": "ModelsUser"
        },
        {
            "name": "commitAffectedFiles",
            "baseName": "commit_affected_files",
            "type": "Array<string>"
        },
        {
            "name": "commitData",
            "baseName": "commit_data",
            "type": "ModelsUser"
        },
        {
            "name": "commitMeta",
            "baseName": "commit_meta",
            "type": "ModelsCommitMeta"
        },
        {
            "name": "parents",
            "baseName": "parents",
            "type": "Array<ModelsCommitMeta>"
        },
        {
            "name": "repoCommit",
            "baseName": "repo_commit",
            "type": "ModelsRepoCommit"
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "ModelsCommitStats"
        }    ];

    static getAttributeTypeMap() {
        return ModelsCommit.attributeTypeMap;
    }
}

