/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ResponseResult {
    'tLogs'?: string;
    'output'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "tLogs",
            "baseName": "_t_logs",
            "type": "string"
        },
        {
            "name": "output",
            "baseName": "output",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ResponseResult.attributeTypeMap;
    }
}

