/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelsApiKeyPackage } from './modelsApiKeyPackage';

export class ResponseGetApiKeyPermissionData {
    'apiKeyPackages'?: Array<ModelsApiKeyPackage>;
    'limitModels'?: boolean;
    'models'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "apiKeyPackages",
            "baseName": "api_key_packages",
            "type": "Array<ModelsApiKeyPackage>"
        },
        {
            "name": "limitModels",
            "baseName": "limit_models",
            "type": "boolean"
        },
        {
            "name": "models",
            "baseName": "models",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ResponseGetApiKeyPermissionData.attributeTypeMap;
    }
}

