/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ResponseGetTaskStatisticsData {
    'totalCost'?: number;
    'totalFailed'?: number;
    'totalRequest'?: number;
    'totalSuccess'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "totalCost",
            "baseName": "total_cost",
            "type": "number"
        },
        {
            "name": "totalFailed",
            "baseName": "total_failed",
            "type": "number"
        },
        {
            "name": "totalRequest",
            "baseName": "total_request",
            "type": "number"
        },
        {
            "name": "totalSuccess",
            "baseName": "total_success",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ResponseGetTaskStatisticsData.attributeTypeMap;
    }
}

