"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsCommit = void 0;
class ModelsCommit {
    static getAttributeTypeMap() {
        return ModelsCommit.attributeTypeMap;
    }
}
exports.ModelsCommit = ModelsCommit;
ModelsCommit.discriminator = undefined;
ModelsCommit.attributeTypeMap = [
    {
        "name": "author",
        "baseName": "author",
        "type": "ModelsUser"
    },
    {
        "name": "commitAffectedFiles",
        "baseName": "commit_affected_files",
        "type": "Array<string>"
    },
    {
        "name": "commitData",
        "baseName": "commit_data",
        "type": "ModelsUser"
    },
    {
        "name": "commitMeta",
        "baseName": "commit_meta",
        "type": "ModelsCommitMeta"
    },
    {
        "name": "parents",
        "baseName": "parents",
        "type": "Array<ModelsCommitMeta>"
    },
    {
        "name": "repoCommit",
        "baseName": "repo_commit",
        "type": "ModelsRepoCommit"
    },
    {
        "name": "stats",
        "baseName": "stats",
        "type": "ModelsCommitStats"
    }
];
