"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsFollow = void 0;
class ModelsFollow {
    static getAttributeTypeMap() {
        return ModelsFollow.attributeTypeMap;
    }
}
exports.ModelsFollow = ModelsFollow;
ModelsFollow.discriminator = undefined;
ModelsFollow.attributeTypeMap = [
    {
        "name": "avatar",
        "baseName": "avatar",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "username",
        "baseName": "username",
        "type": "string"
    }
];
