"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsMember = void 0;
class ModelsMember {
    static getAttributeTypeMap() {
        return ModelsMember.attributeTypeMap;
    }
}
exports.ModelsMember = ModelsMember;
ModelsMember.discriminator = undefined;
ModelsMember.attributeTypeMap = [
    {
        "name": "avatarUrl",
        "baseName": "avatar_url",
        "type": "string"
    },
    {
        "name": "fullName",
        "baseName": "full_name",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "username",
        "baseName": "username",
        "type": "string"
    }
];
