"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsApiKeyInfo = void 0;
class ModelsApiKeyInfo {
    static getAttributeTypeMap() {
        return ModelsApiKeyInfo.attributeTypeMap;
    }
}
exports.ModelsApiKeyInfo = ModelsApiKeyInfo;
ModelsApiKeyInfo.discriminator = undefined;
ModelsApiKeyInfo.attributeTypeMap = [
    {
        "name": "apiPrice",
        "baseName": "api_price",
        "type": "number"
    },
    {
        "name": "commitHash",
        "baseName": "commit_hash",
        "type": "string"
    },
    {
        "name": "inputFormat",
        "baseName": "input_format",
        "type": "{ [key: string]: any; }"
    },
    {
        "name": "modelDescription",
        "baseName": "model_description",
        "type": "string"
    },
    {
        "name": "modelId",
        "baseName": "model_id",
        "type": "string"
    },
    {
        "name": "outputFormat",
        "baseName": "output_format",
        "type": "{ [key: string]: any; }"
    }
];
