"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsQueueTask = void 0;
class ModelsQueueTask {
    static getAttributeTypeMap() {
        return ModelsQueueTask.attributeTypeMap;
    }
}
exports.ModelsQueueTask = ModelsQueueTask;
ModelsQueueTask.discriminator = undefined;
ModelsQueueTask.attributeTypeMap = [
    {
        "name": "action",
        "baseName": "action",
        "type": "string"
    },
    {
        "name": "createdAt",
        "baseName": "created_at",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "objectId",
        "baseName": "object_id",
        "type": "string"
    },
    {
        "name": "objectName",
        "baseName": "object_name",
        "type": "string"
    },
    {
        "name": "result",
        "baseName": "result",
        "type": "{ [key: string]: any; }"
    },
    {
        "name": "state",
        "baseName": "state",
        "type": "string"
    },
    {
        "name": "updatedAt",
        "baseName": "updated_at",
        "type": "string"
    },
    {
        "name": "userId",
        "baseName": "user_id",
        "type": "string"
    }
];
