"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsOffer = void 0;
class ModelsOffer {
    static getAttributeTypeMap() {
        return ModelsOffer.attributeTypeMap;
    }
}
exports.ModelsOffer = ModelsOffer;
ModelsOffer.discriminator = undefined;
ModelsOffer.attributeTypeMap = [
    {
        "name": "createdAt",
        "baseName": "created_at",
        "type": "number"
    },
    {
        "name": "createdBy",
        "baseName": "created_by",
        "type": "string"
    },
    {
        "name": "expAt",
        "baseName": "exp_at",
        "type": "number"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "orgUsername",
        "baseName": "org_username",
        "type": "string"
    },
    {
        "name": "role",
        "baseName": "role",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    },
    {
        "name": "username",
        "baseName": "username",
        "type": "string"
    }
];
