/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
export declare class ModelsModelVersioning {
    'commitHash'?: string;
    'commitMessage'?: string;
    'createdAt'?: string;
    'dependency'?: {
        [key: string]: any;
    };
    'id'?: string;
    'inputFormat'?: {
        [key: string]: any;
    };
    'modelId'?: string;
    'nodeReward'?: number;
    'outputFormat'?: {
        [key: string]: any;
    };
    'platform'?: string;
    'sysRequire'?: {
        [key: string]: any;
    };
    'testResult'?: {
        [key: string]: any;
    };
    'updatedAt'?: string;
    'verifyStatus'?: string;
    'verifyTaskId'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
