"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsApiKeyHistories = void 0;
class ModelsApiKeyHistories {
    static getAttributeTypeMap() {
        return ModelsApiKeyHistories.attributeTypeMap;
    }
}
exports.ModelsApiKeyHistories = ModelsApiKeyHistories;
ModelsApiKeyHistories.discriminator = undefined;
ModelsApiKeyHistories.attributeTypeMap = [
    {
        "name": "createdAt",
        "baseName": "created_at",
        "type": "string"
    },
    {
        "name": "modelId",
        "baseName": "model_id",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    },
    {
        "name": "taskId",
        "baseName": "task_id",
        "type": "string"
    },
    {
        "name": "updatedAt",
        "baseName": "updated_at",
        "type": "string"
    }
];
