"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsRepoCommit = void 0;
class ModelsRepoCommit {
    static getAttributeTypeMap() {
        return ModelsRepoCommit.attributeTypeMap;
    }
}
exports.ModelsRepoCommit = ModelsRepoCommit;
ModelsRepoCommit.discriminator = undefined;
ModelsRepoCommit.attributeTypeMap = [
    {
        "name": "author",
        "baseName": "author",
        "type": "ModelsCommitUser"
    },
    {
        "name": "committer",
        "baseName": "committer",
        "type": "ModelsCommitUser"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "tree",
        "baseName": "tree",
        "type": "ModelsCommitMeta"
    }
];
