"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsWallet = void 0;
class ModelsWallet {
    static getAttributeTypeMap() {
        return ModelsWallet.attributeTypeMap;
    }
}
exports.ModelsWallet = ModelsWallet;
ModelsWallet.discriminator = undefined;
ModelsWallet.attributeTypeMap = [
    {
        "name": "balance",
        "baseName": "balance",
        "type": "number"
    },
    {
        "name": "debt",
        "baseName": "debt",
        "type": "number"
    },
    {
        "name": "earnings",
        "baseName": "earnings",
        "type": "number"
    },
    {
        "name": "freeBalance",
        "baseName": "free_balance",
        "type": "number"
    }
];
