/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsPlatformTask } from './modelsPlatformTask';
export declare class ModelsModelVersioningGroupLite {
    /**
    * Dependency        map[string]interface{} `json:\"dependency\"`
    */
    'commitHash'?: string;
    /**
    * TestResult        map[string]interface{} `json:\"test_result\"` InputFormat       map[string]interface{} `json:\"input_format\"` OutputFormat      map[string]interface{} `json:\"output_format\"` SysRequired       map[string]interface{} `json:\"sys_require\"`
    */
    'commitMessage'?: string;
    'isActive'?: boolean;
    'lastCheckedAt'?: string;
    'modelId'?: string;
    'pendingPlatforms'?: Array<ModelsPlatformTask>;
    'rejectedPlatforms'?: Array<ModelsPlatformTask>;
    'verifiedPlatforms'?: Array<ModelsPlatformTask>;
    'verifyStatus'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
