"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsModelVersioningGroupLite = void 0;
class ModelsModelVersioningGroupLite {
    static getAttributeTypeMap() {
        return ModelsModelVersioningGroupLite.attributeTypeMap;
    }
}
exports.ModelsModelVersioningGroupLite = ModelsModelVersioningGroupLite;
ModelsModelVersioningGroupLite.discriminator = undefined;
ModelsModelVersioningGroupLite.attributeTypeMap = [
    {
        "name": "commitHash",
        "baseName": "commit_hash",
        "type": "string"
    },
    {
        "name": "commitMessage",
        "baseName": "commit_message",
        "type": "string"
    },
    {
        "name": "isActive",
        "baseName": "is_active",
        "type": "boolean"
    },
    {
        "name": "lastCheckedAt",
        "baseName": "last_checked_at",
        "type": "string"
    },
    {
        "name": "modelId",
        "baseName": "model_id",
        "type": "string"
    },
    {
        "name": "pendingPlatforms",
        "baseName": "pending_platforms",
        "type": "Array<ModelsPlatformTask>"
    },
    {
        "name": "rejectedPlatforms",
        "baseName": "rejected_platforms",
        "type": "Array<ModelsPlatformTask>"
    },
    {
        "name": "verifiedPlatforms",
        "baseName": "verified_platforms",
        "type": "Array<ModelsPlatformTask>"
    },
    {
        "name": "verifyStatus",
        "baseName": "verify_status",
        "type": "string"
    }
];
