"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsUser = void 0;
class ModelsUser {
    static getAttributeTypeMap() {
        return ModelsUser.attributeTypeMap;
    }
}
exports.ModelsUser = ModelsUser;
ModelsUser.discriminator = undefined;
ModelsUser.attributeTypeMap = [
    {
        "name": "allowRequestToJoin",
        "baseName": "allow_request_to_join",
        "type": "boolean"
    },
    {
        "name": "avatarUrl",
        "baseName": "avatar_url",
        "type": "string"
    },
    {
        "name": "bio",
        "baseName": "bio",
        "type": "string"
    },
    {
        "name": "blocked",
        "baseName": "blocked",
        "type": "boolean"
    },
    {
        "name": "blockedAt",
        "baseName": "blocked_at",
        "type": "string"
    },
    {
        "name": "email",
        "baseName": "email",
        "type": "string"
    },
    {
        "name": "followers",
        "baseName": "followers",
        "type": "Array<ModelsFollow>"
    },
    {
        "name": "followersCount",
        "baseName": "followers_count",
        "type": "number"
    },
    {
        "name": "followings",
        "baseName": "followings",
        "type": "Array<ModelsFollow>"
    },
    {
        "name": "followingsCount",
        "baseName": "followings_count",
        "type": "number"
    },
    {
        "name": "githubLink",
        "baseName": "github_link",
        "type": "string"
    },
    {
        "name": "githubName",
        "baseName": "github_name",
        "type": "string"
    },
    {
        "name": "homePageName",
        "baseName": "home_page_name",
        "type": "string"
    },
    {
        "name": "id",
        "baseName": "id",
        "type": "string"
    },
    {
        "name": "interests",
        "baseName": "interests",
        "type": "string"
    },
    {
        "name": "inviteOffers",
        "baseName": "invite_offers",
        "type": "Array<ModelsOffer>"
    },
    {
        "name": "inviteOffersCount",
        "baseName": "invite_offers_count",
        "type": "number"
    },
    {
        "name": "isFollowing",
        "baseName": "is_following",
        "type": "boolean"
    },
    {
        "name": "joinId",
        "baseName": "join_id",
        "type": "string"
    },
    {
        "name": "joinOffers",
        "baseName": "join_offers",
        "type": "Array<ModelsOffer>"
    },
    {
        "name": "joinOffersCount",
        "baseName": "join_offers_count",
        "type": "number"
    },
    {
        "name": "members",
        "baseName": "members",
        "type": "Array<ModelsMember>"
    },
    {
        "name": "membersCount",
        "baseName": "members_count",
        "type": "number"
    },
    {
        "name": "name",
        "baseName": "name",
        "type": "string"
    },
    {
        "name": "role",
        "baseName": "role",
        "type": "string"
    },
    {
        "name": "token",
        "baseName": "token",
        "type": "string"
    },
    {
        "name": "twitterLink",
        "baseName": "twitter_link",
        "type": "string"
    },
    {
        "name": "twitterName",
        "baseName": "twitter_name",
        "type": "string"
    },
    {
        "name": "type",
        "baseName": "type",
        "type": "string"
    },
    {
        "name": "username",
        "baseName": "username",
        "type": "string"
    },
    {
        "name": "verified",
        "baseName": "verified",
        "type": "boolean"
    },
    {
        "name": "visibility",
        "baseName": "visibility",
        "type": "string"
    },
    {
        "name": "wallet",
        "baseName": "wallet",
        "type": "ModelsWallet"
    },
    {
        "name": "walletAddress",
        "baseName": "wallet_address",
        "type": "string"
    },
    {
        "name": "walletConnection",
        "baseName": "wallet_connection",
        "type": "string"
    }
];
