"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsCommitMeta = void 0;
class ModelsCommitMeta {
    static getAttributeTypeMap() {
        return ModelsCommitMeta.attributeTypeMap;
    }
}
exports.ModelsCommitMeta = ModelsCommitMeta;
ModelsCommitMeta.discriminator = undefined;
ModelsCommitMeta.attributeTypeMap = [
    {
        "name": "created",
        "baseName": "created",
        "type": "string"
    },
    {
        "name": "sha",
        "baseName": "sha",
        "type": "string"
    },
    {
        "name": "url",
        "baseName": "url",
        "type": "string"
    }
];
