"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsPlatformTask = void 0;
class ModelsPlatformTask {
    static getAttributeTypeMap() {
        return ModelsPlatformTask.attributeTypeMap;
    }
}
exports.ModelsPlatformTask = ModelsPlatformTask;
ModelsPlatformTask.discriminator = undefined;
ModelsPlatformTask.attributeTypeMap = [
    {
        "name": "platform",
        "baseName": "platform",
        "type": "string"
    },
    {
        "name": "testResult",
        "baseName": "test_result",
        "type": "{ [key: string]: any; }"
    },
    {
        "name": "updatedAt",
        "baseName": "updated_at",
        "type": "string"
    },
    {
        "name": "verifyTaskId",
        "baseName": "verify_task_id",
        "type": "string"
    }
];
