"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsApiKeyPackage = void 0;
class ModelsApiKeyPackage {
    static getAttributeTypeMap() {
        return ModelsApiKeyPackage.attributeTypeMap;
    }
}
exports.ModelsApiKeyPackage = ModelsApiKeyPackage;
ModelsApiKeyPackage.discriminator = undefined;
ModelsApiKeyPackage.attributeTypeMap = [
    {
        "name": "modelId",
        "baseName": "model_id",
        "type": "string"
    },
    {
        "name": "usesRemaining",
        "baseName": "uses_remaining",
        "type": "number"
    }
];
