/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsCommitMeta } from './modelsCommitMeta';
import { ModelsCommitStats } from './modelsCommitStats';
import { ModelsRepoCommit } from './modelsRepoCommit';
import { ModelsUser } from './modelsUser';
export declare class ModelsCommit {
    'author'?: ModelsUser;
    'commitAffectedFiles'?: Array<string>;
    'commitData'?: ModelsUser;
    'commitMeta'?: ModelsCommitMeta;
    'parents'?: Array<ModelsCommitMeta>;
    'repoCommit'?: ModelsRepoCommit;
    'stats'?: ModelsCommitStats;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
