"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModelsCommitStats = void 0;
class ModelsCommitStats {
    static getAttributeTypeMap() {
        return ModelsCommitStats.attributeTypeMap;
    }
}
exports.ModelsCommitStats = ModelsCommitStats;
ModelsCommitStats.discriminator = undefined;
ModelsCommitStats.attributeTypeMap = [
    {
        "name": "additions",
        "baseName": "additions",
        "type": "number"
    },
    {
        "name": "deletions",
        "baseName": "deletions",
        "type": "number"
    },
    {
        "name": "total",
        "baseName": "total",
        "type": "number"
    }
];
