/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsFollow } from './modelsFollow';
import { ModelsMember } from './modelsMember';
import { ModelsOffer } from './modelsOffer';
import { ModelsWallet } from './modelsWallet';
export declare class ModelsUser {
    'allowRequestToJoin'?: boolean;
    'avatarUrl'?: string;
    'bio'?: string;
    'blocked'?: boolean;
    'blockedAt'?: string;
    'email'?: string;
    'followers'?: Array<ModelsFollow>;
    'followersCount'?: number;
    'followings'?: Array<ModelsFollow>;
    'followingsCount'?: number;
    'githubLink'?: string;
    'githubName'?: string;
    'homePageName'?: string;
    'id'?: string;
    'interests'?: string;
    'inviteOffers'?: Array<ModelsOffer>;
    'inviteOffersCount'?: number;
    'isFollowing'?: boolean;
    'joinId'?: string;
    'joinOffers'?: Array<ModelsOffer>;
    'joinOffersCount'?: number;
    'members'?: Array<ModelsMember>;
    'membersCount'?: number;
    'name'?: string;
    'role'?: string;
    'token'?: string;
    'twitterLink'?: string;
    'twitterName'?: string;
    'type'?: string;
    'username'?: string;
    'verified'?: boolean;
    'visibility'?: string;
    'wallet'?: ModelsWallet;
    'walletAddress'?: string;
    'walletConnection'?: string;
    static discriminator: string | undefined;
    static attributeTypeMap: Array<{
        name: string;
        baseName: string;
        type: string;
    }>;
    static getAttributeTypeMap(): {
        name: string;
        baseName: string;
        type: string;
    }[];
}
