"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestCheckValidToVerifyAiModelRequest = void 0;
class RequestCheckValidToVerifyAiModelRequest {
    static getAttributeTypeMap() {
        return RequestCheckValidToVerifyAiModelRequest.attributeTypeMap;
    }
}
exports.RequestCheckValidToVerifyAiModelRequest = RequestCheckValidToVerifyAiModelRequest;
RequestCheckValidToVerifyAiModelRequest.discriminator = undefined;
RequestCheckValidToVerifyAiModelRequest.attributeTypeMap = [
    {
        "name": "commitHash",
        "baseName": "commit_hash",
        "type": "string"
    },
    {
        "name": "platforms",
        "baseName": "platforms",
        "type": "Array<string>"
    }
];
