"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestDistributeTaskRequest = void 0;
class RequestDistributeTaskRequest {
    static getAttributeTypeMap() {
        return RequestDistributeTaskRequest.attributeTypeMap;
    }
}
exports.RequestDistributeTaskRequest = RequestDistributeTaskRequest;
RequestDistributeTaskRequest.discriminator = undefined;
RequestDistributeTaskRequest.attributeTypeMap = [
    {
        "name": "files",
        "baseName": "files",
        "type": "Array<object>"
    },
    {
        "name": "inputParams",
        "baseName": "input_params",
        "type": "{ [key: string]: any; }"
    },
    {
        "name": "modelId",
        "baseName": "model_id",
        "type": "string"
    }
];
