"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestGetApiKeyStatisticsByModelIdRequest = void 0;
class RequestGetApiKeyStatisticsByModelIdRequest {
    static getAttributeTypeMap() {
        return RequestGetApiKeyStatisticsByModelIdRequest.attributeTypeMap;
    }
}
exports.RequestGetApiKeyStatisticsByModelIdRequest = RequestGetApiKeyStatisticsByModelIdRequest;
RequestGetApiKeyStatisticsByModelIdRequest.discriminator = undefined;
RequestGetApiKeyStatisticsByModelIdRequest.attributeTypeMap = [
    {
        "name": "from",
        "baseName": "from",
        "type": "string"
    },
    {
        "name": "to",
        "baseName": "to",
        "type": "string"
    }
];
