"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RequestCalculateCostToVerifyAiModelRequest = void 0;
class RequestCalculateCostToVerifyAiModelRequest {
    static getAttributeTypeMap() {
        return RequestCalculateCostToVerifyAiModelRequest.attributeTypeMap;
    }
}
exports.RequestCalculateCostToVerifyAiModelRequest = RequestCalculateCostToVerifyAiModelRequest;
RequestCalculateCostToVerifyAiModelRequest.discriminator = undefined;
RequestCalculateCostToVerifyAiModelRequest.attributeTypeMap = [
    {
        "name": "commitHash",
        "baseName": "commit_hash",
        "type": "string"
    },
    {
        "name": "platforms",
        "baseName": "platforms",
        "type": "Array<string>"
    }
];
