"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseCheckValidToVerifyAiModelData = void 0;
class ResponseCheckValidToVerifyAiModelData {
    static getAttributeTypeMap() {
        return ResponseCheckValidToVerifyAiModelData.attributeTypeMap;
    }
}
exports.ResponseCheckValidToVerifyAiModelData = ResponseCheckValidToVerifyAiModelData;
ResponseCheckValidToVerifyAiModelData.discriminator = undefined;
ResponseCheckValidToVerifyAiModelData.attributeTypeMap = [
    {
        "name": "valid",
        "baseName": "valid",
        "type": "boolean"
    }
];
