"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseResult = void 0;
class ResponseResult {
    static getAttributeTypeMap() {
        return ResponseResult.attributeTypeMap;
    }
}
exports.ResponseResult = ResponseResult;
ResponseResult.discriminator = undefined;
ResponseResult.attributeTypeMap = [
    {
        "name": "tLogs",
        "baseName": "_t_logs",
        "type": "string"
    },
    {
        "name": "output",
        "baseName": "output",
        "type": "string"
    }
];
