"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseGetCommitHistoryResponse = void 0;
class ResponseGetCommitHistoryResponse {
    constructor() {
        this['status'] = 'success';
    }
    static getAttributeTypeMap() {
        return ResponseGetCommitHistoryResponse.attributeTypeMap;
    }
}
exports.ResponseGetCommitHistoryResponse = ResponseGetCommitHistoryResponse;
ResponseGetCommitHistoryResponse.discriminator = undefined;
ResponseGetCommitHistoryResponse.attributeTypeMap = [
    {
        "name": "data",
        "baseName": "data",
        "type": "ResponseGetCommitHistoryData"
    },
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    }
];
