"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseModelVersioningGroupLiteListData = void 0;
class ResponseModelVersioningGroupLiteListData {
    static getAttributeTypeMap() {
        return ResponseModelVersioningGroupLiteListData.attributeTypeMap;
    }
}
exports.ResponseModelVersioningGroupLiteListData = ResponseModelVersioningGroupLiteListData;
ResponseModelVersioningGroupLiteListData.discriminator = undefined;
ResponseModelVersioningGroupLiteListData.attributeTypeMap = [
    {
        "name": "records",
        "baseName": "records",
        "type": "Array<ModelsModelVersioningGroupLite>"
    },
    {
        "name": "total",
        "baseName": "total",
        "type": "number"
    }
];
