"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseCheckModelIsServingData = void 0;
class ResponseCheckModelIsServingData {
    static getAttributeTypeMap() {
        return ResponseCheckModelIsServingData.attributeTypeMap;
    }
}
exports.ResponseCheckModelIsServingData = ResponseCheckModelIsServingData;
ResponseCheckModelIsServingData.discriminator = undefined;
ResponseCheckModelIsServingData.attributeTypeMap = [
    {
        "name": "consumers",
        "baseName": "consumers",
        "type": "number"
    },
    {
        "name": "serving",
        "baseName": "serving",
        "type": "boolean"
    }
];
