"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseGetTaskStatisticsData = void 0;
class ResponseGetTaskStatisticsData {
    static getAttributeTypeMap() {
        return ResponseGetTaskStatisticsData.attributeTypeMap;
    }
}
exports.ResponseGetTaskStatisticsData = ResponseGetTaskStatisticsData;
ResponseGetTaskStatisticsData.discriminator = undefined;
ResponseGetTaskStatisticsData.attributeTypeMap = [
    {
        "name": "totalCost",
        "baseName": "total_cost",
        "type": "number"
    },
    {
        "name": "totalFailed",
        "baseName": "total_failed",
        "type": "number"
    },
    {
        "name": "totalRequest",
        "baseName": "total_request",
        "type": "number"
    },
    {
        "name": "totalSuccess",
        "baseName": "total_success",
        "type": "number"
    }
];
