"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseEstimateCostData = void 0;
class ResponseEstimateCostData {
    constructor() {
        this['symbol'] = '$';
        this['unit'] = 'USD';
    }
    static getAttributeTypeMap() {
        return ResponseEstimateCostData.attributeTypeMap;
    }
}
exports.ResponseEstimateCostData = ResponseEstimateCostData;
ResponseEstimateCostData.discriminator = undefined;
ResponseEstimateCostData.attributeTypeMap = [
    {
        "name": "cost",
        "baseName": "cost",
        "type": "number"
    },
    {
        "name": "symbol",
        "baseName": "symbol",
        "type": "string"
    },
    {
        "name": "unit",
        "baseName": "unit",
        "type": "string"
    }
];
