"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseGetApiKeyPermissionData = void 0;
class ResponseGetApiKeyPermissionData {
    static getAttributeTypeMap() {
        return ResponseGetApiKeyPermissionData.attributeTypeMap;
    }
}
exports.ResponseGetApiKeyPermissionData = ResponseGetApiKeyPermissionData;
ResponseGetApiKeyPermissionData.discriminator = undefined;
ResponseGetApiKeyPermissionData.attributeTypeMap = [
    {
        "name": "apiKeyPackages",
        "baseName": "api_key_packages",
        "type": "Array<ModelsApiKeyPackage>"
    },
    {
        "name": "limitModels",
        "baseName": "limit_models",
        "type": "boolean"
    },
    {
        "name": "models",
        "baseName": "models",
        "type": "Array<string>"
    }
];
