"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseFailResponse = void 0;
class ResponseFailResponse {
    constructor() {
        this['status'] = 'fail';
    }
    static getAttributeTypeMap() {
        return ResponseFailResponse.attributeTypeMap;
    }
}
exports.ResponseFailResponse = ResponseFailResponse;
ResponseFailResponse.discriminator = undefined;
ResponseFailResponse.attributeTypeMap = [
    {
        "name": "message",
        "baseName": "message",
        "type": "string"
    },
    {
        "name": "status",
        "baseName": "status",
        "type": "string"
    }
];
