"use strict";
/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ResponseGetCommitHistoryData = void 0;
class ResponseGetCommitHistoryData {
    static getAttributeTypeMap() {
        return ResponseGetCommitHistoryData.attributeTypeMap;
    }
}
exports.ResponseGetCommitHistoryData = ResponseGetCommitHistoryData;
ResponseGetCommitHistoryData.discriminator = undefined;
ResponseGetCommitHistoryData.attributeTypeMap = [
    {
        "name": "commit",
        "baseName": "commit",
        "type": "Array<ModelsCommit>"
    },
    {
        "name": "hasMore",
        "baseName": "has_more",
        "type": "boolean"
    },
    {
        "name": "lastPage",
        "baseName": "last_page",
        "type": "number"
    }
];
