@BASE_URL=http://143.198.81.10:9000/api/v1/
@TASK_ID=aea6944c-a808-4c11-b8de-557fe02d505f
@FROM=2023-05-07%2015:04:05
@TO=2023-05-08%2015:04:05
@MODEL_ID=7332d265-171e-4055-9f2f-af51a52a82c4
@HUB_TASK_ID =c2a6e7f5-15b4-461f-9b8a-4bcb8f8c4bcd
@BASE_URL=http://143.198.81.10:9000/api/v1/
@API_KEY=d9eb2842bb95039bfc31196432a82998bc5930f4
@COMMIT_HASH=ba271f290d732d6aa5902bf4d42103b516fcb7c2
@VERIFY_STATUS=verified
@LIMIT=10
@OFFSET=0
@OWNER=bohaha123-3333
@REPO=HEHEE
@PATH=
@SHA=master
@PAGE=1
@PAGE_SIZE=10
@REPO_TYPE=

### Cancel task
DELETE {{BASE_URL}}api-key/task/{{TASK_ID}}/cancel
x-api-key: {{API_KEY}}

### Get Balance
GET {{BASE_URL}}api-key/balance
x-api-key: {{API_KEY}}

###
GET {{BASE_URL}}api-key/repository/{{OWNER}}/{{REPO}}/commit/history?path={{PATH}}&sha={{SHA}}&page={{PAGE}}&pageSize={{PAGE_SIZE}}&repoType={{REPO_TYPE}}
x-api-key: {{API_KEY}}

###
GET {{BASE_URL}}api-key/model/{{MODEL_ID}}/versioning/list?offset={{OFFSET}}&limit={{LIMIT}}&verifyStatus={{VERIFY_STATUS}}
x-api-key: {{API_KEY}}


###
DELETE {{BASE_URL}}api-key/model/{{MODEL_ID}}/versioning?commitHash={{COMMIT_HASH}}
x-api-key: {{API_KEY}}

###
PUT {{BASE_URL}}api-key/model/{{MODEL_ID}}/versioning?commitHash={{COMMIT_HASH}}
x-api-key: {{API_KEY}}

###
GET {{BASE_URL}}api-key/model/{{MODEL_ID}}/versioning
x-api-key: {{API_KEY}}

###
POST {{BASE_URL}}api-key/model/{{MODEL_ID}}/statistics
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "from": "2023-05-07 15:04:05",
  "to": "2023-05-07 15:04:05"
}

###
GET {{BASE_URL}}api-key/model/{{MODEL_ID}}/task/cost
x-api-key: {{API_KEY}}

###
GET {{BASE_URL}}api-key/model/{{MODEL_ID}}/serving
x-api-key: {{API_KEY}}

### Get Supported Platforms
GET {{BASE_URL}}api-key/model/verify/support/platforms
x-api-key: {{API_KEY}}



###
POST {{BASE_URL}}api-key/model/{{MODEL_ID}}/verify/cost
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "commit_hash": "{{COMMIT_HASH}}",
  "platforms": ["linux", "windows"]
}

###
POST {{BASE_URL}}api-key/model/{{MODEL_ID}}/verify
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "commit_hash": "{{COMMIT_HASH}}",
  "platforms": ["linux", "windows"]
}


### Post Check valid source code to verify ai model by api key
POST {{BASE_URL}}api-key/model/{{MODEL_ID}}/pre-verify
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "commit_hash": "{{COMMIT_HASH}}",
  "platforms": ["linux", "windows"]
}


### Get Verify Task by Model Id + Commit Hash + Status
GET {{BASE_URL}}api-key/model/{{MODEL_ID}}/verify/task?commitHash={{COMMIT_HASH}}&verifyStatus={{VERIFY_STATUS}}
x-api-key: {{API_KEY}}


### Get Verify Platform task by api key
GET {{BASE_URL}}api-key/model/verify/platform/task/{{HUB_TASK_ID}}
x-api-key: {{API_KEY}}

### Get Model Versioning By Hub Task Id by api key
GET {{BASE_URL}}api-key/model/verify/hub/task/{{HUB_TASK_ID}}
x-api-key: {{API_KEY}}

### Post Distribute Task
POST {{BASE_URL}}api-key/task
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "model_id": "{{MODEL_ID}}",
  "files": [
    {
    "data":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Cat_August_2010-4.jpg/1200px-Cat_August_2010-4.jpg"
    }
  ],
  "input_params": {}
}



### Post API Key Statistics
POST {{BASE_URL}}api-key/statistics
Content-Type: application/json
x-api-key: {{API_KEY}}

{
  "from": "{{FROM}}",
  "to": "{{TO}}"
}


### Get Tasks Result
GET {{BASE_URL}}api-key/task/{{TASK_ID}}/result
x-api-key: {{API_KEY}}

### Get Tasks Histories
GET {{BASE_URL}}api-key/task/histories?limit={{LIMIT}}&offset={{OFFSET}}
x-api-key: {{API_KEY}}


### Get Api Key Permission
GET {{BASE_URL}}api-key/permission
x-api-key: {{API_KEY}}

