/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ModelsWallet {
    'balance'?: number;
    'debt'?: number;
    'earnings'?: number;
    'freeBalance'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "debt",
            "baseName": "debt",
            "type": "number"
        },
        {
            "name": "earnings",
            "baseName": "earnings",
            "type": "number"
        },
        {
            "name": "freeBalance",
            "baseName": "free_balance",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ModelsWallet.attributeTypeMap;
    }
}

