/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelsCommitMeta } from './modelsCommitMeta';
import { ModelsCommitUser } from './modelsCommitUser';

export class ModelsRepoCommit {
    'author'?: ModelsCommitUser;
    'committer'?: ModelsCommitUser;
    'message'?: string;
    'tree'?: ModelsCommitMeta;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "author",
            "baseName": "author",
            "type": "ModelsCommitUser"
        },
        {
            "name": "committer",
            "baseName": "committer",
            "type": "ModelsCommitUser"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "tree",
            "baseName": "tree",
            "type": "ModelsCommitMeta"
        }    ];

    static getAttributeTypeMap() {
        return ModelsRepoCommit.attributeTypeMap;
    }
}

