/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ModelsApiKeyPackage {
    'modelId'?: string;
    'usesRemaining'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "string"
        },
        {
            "name": "usesRemaining",
            "baseName": "uses_remaining",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ModelsApiKeyPackage.attributeTypeMap;
    }
}

