/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RequestDistributeTaskRequest {
    'files'?: Array<object>;
    'inputParams'?: { [key: string]: any; };
    'modelId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<object>"
        },
        {
            "name": "inputParams",
            "baseName": "input_params",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "modelId",
            "baseName": "model_id",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RequestDistributeTaskRequest.attributeTypeMap;
    }
}

