/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ResponseGetApiKeyPermissionData } from './responseGetApiKeyPermissionData';

export class ResponseGetApiKeyPermissionResponse {
    'data'?: ResponseGetApiKeyPermissionData;
    'message'?: string;
    'status'?: string = 'success';

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "ResponseGetApiKeyPermissionData"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ResponseGetApiKeyPermissionResponse.attributeTypeMap;
    }
}

