/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelsApiKeyHistories } from './modelsApiKeyHistories';

export class ResponseApiKeyHistoryListData {
    'records'?: Array<ModelsApiKeyHistories>;
    'total'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "records",
            "baseName": "records",
            "type": "Array<ModelsApiKeyHistories>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ResponseApiKeyHistoryListData.attributeTypeMap;
    }
}

