/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ResponseCheckValidToVerifyAiModelData {
    'valid'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "valid",
            "baseName": "valid",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ResponseCheckValidToVerifyAiModelData.attributeTypeMap;
    }
}

