/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ModelsCommit } from './modelsCommit';

export class ResponseGetCommitHistoryData {
    'commit'?: Array<ModelsCommit>;
    'hasMore'?: boolean;
    'lastPage'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "commit",
            "baseName": "commit",
            "type": "Array<ModelsCommit>"
        },
        {
            "name": "hasMore",
            "baseName": "has_more",
            "type": "boolean"
        },
        {
            "name": "lastPage",
            "baseName": "last_page",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ResponseGetCommitHistoryData.attributeTypeMap;
    }
}

