/**
 * AIOZ-AI-PLATFORM API
 * API for AIOZ AI Platform
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ResponseResult } from './responseResult';

export class ResponseGetTaskResultData {
    'result'?: ResponseResult;
    'status'?: string;
    'success'?: boolean;
    'traceback'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "result",
            "baseName": "result",
            "type": "ResponseResult"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "traceback",
            "baseName": "traceback",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ResponseGetTaskResultData.attributeTypeMap;
    }
}

